export const tagPrompts = [
  'What can you tell me about his [tag] experience?',
  'How deep is his knowledge of [tag]?',
  "What's his track record with [tag]?",
  'How experienced is he with [tag]?',
  "What's his proficiency level in [tag]?",
  'How much [tag] work has he done?',
  "What's his background using [tag]?",
  'How well does he know [tag]?',
  "What's his exposure to [tag]?",
  'How familiar is he with [tag]?',
  'What [tag] projects has he tackled?',
  'How extensively has he worked with [tag]?',
  'Any [tag] expertise worth mentioning?',
  "What's his [tag] skill level?",
  'How comfortable is he with [tag]?',
  'What [tag] work has he shipped?',
  'How much [tag] development has he done?',
  "What's his hands-on [tag] experience?",
  'How proficient is he in [tag]?',
  'What [tag] implementations has he built?',
  "What's his [tag] development history?",
  'How deep does his [tag] knowledge go?',
  'What [tag] solutions has he created?',
  'How skilled is he with [tag]?',
  'What [tag] systems has he worked on?',
  'How much [tag] coding has he done?',
  "What's his [tag] project portfolio?",
  'How advanced is his [tag] usage?',
  'What [tag] applications has he built?',
  'How strong is his [tag] foundation?',
  'What [tag] frameworks has he mastered?',
  'How competent is he with [tag]?',
  'How seasoned is he with [tag]?',
  'How capable is he with [tag]?',
  'How thorough is his [tag] understanding?',
  'How practiced is he with [tag]?',
  'How solid is his [tag] expertise?',
  'How versatile is he with [tag]?',
]
